name: Update data by dispatch

# https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
on:
    workflow_dispatch:
        inputs:
            data:
                description: 'Data'
                required: true

jobs:
    update:
        name: Update data
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                node-version: 12.x
            - run: echo "${{ github.event.inputs.data }}" > data.txt
            - name: Push changes
              run: |
                git add data.txt
                git commit -m "Update data.txt"
                git push
